### ISSUE TITLE
Fix `h3` margins

### ISSUE THREAD

**Issue by DanielGarc** [DanielGarc/ana-portfolio-website#3]
This [commit](https://github.com/DanielGarc/ana-portfolio-website/commit/55df21bef3eb5dfff3e2ef843f8217a08b0e0fd8) broke some of the existing margins, go back and track where h3 was used and fix margin
e.g. in /fitstudy
![image](https://user-images.githubusercontent.com/7727153/77598660-65e54a80-6ed0-11ea-96a7-949c90a48984.png)

**Comment by anarosals** [comment]
I'll work on this!
